package:
  name: kmergenetyper
  version: 1.0.13

source:
  url: https://github.com/genomicepidemiology/kmergenetyper/archive/refs/tags/v1.0.16.tar.gz


build:
  number: 2
  skip: True  # [py<34]

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

about:
  home: https://github.com/genomicepidemiology/kmergenetyper
  summary: 'Kmergenetyper test.'
  license: Apache-2.0