about:
  home: https://github.com/genomicepidemiology/kmergenetyper
  license: Apache-2.0
  summary: Kmergenetyper test.
build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv'
package:
  name: kmergenetyper
  version: 1.1.11
requirements:
  host:
  - python >=3.6
  - pip
  run:
  - python >=3.6
  - kma >=1.4.9
source:
  url: https://github.com/genomicepidemiology/kmergenetyper/archive/refs/tags/1.1.11.tar.gz
