package:
  name: kmergenetyper
  version: 1.0.13

source:
  url: https://github.com/genomicepidemiology/kmergenetyper/archive/refs/tags/v1.0.16.tar.gz

build:
  number: 2

requirements:
  build:
    - python >=3.6
    - pip
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pip

about:
  home: https://github.com/genomicepidemiology/kmergenetyper
  summary: 'Kmergenetyper test.'
  license: Apache-2.0