package:
  name: kmergenetyper
  version: 1.0.13

source:
  url: https://github.com/genomicepidemiology/kmergenetyper/archive/refs/tags/v1.1.0.tar.gz


build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - kma >=1.4.9
about:
  home: https://github.com/genomicepidemiology/kmergenetyper
  summary: 'Kmergenetyper test.'
  license: Apache-2.0