package:
  name: kmergenetyper
  version: 1.0.13

source:
  url: https://github.com/genomicepidemiology/kmergenetyper

build:
  number: 2

requirements:
  build:
    - python >=3.8
    - pip
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pip

about:
  home: https://github.com/genomicepidemiology/kmergenetyper
  summary: 'Kmergenetyper test.'
  license: Apache-2.0